import type { Metadata } from "next";
import "./globals.css";
import { CardsContextProvider } from "@/context/CardsContext";
import {
  baskerville,
  cinzel,
  cormorant,
  fell,
  geistMono,
  geistSans,
  inter,
} from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cinzel.variable} ${cormorant.variable} ${baskerville.variable} ${fell.variable} ${inter.variable} antialiased`}
      >
        <CardsContextProvider>{children}</CardsContextProvider>
      </body>
    </html>
  );
}
