import { CardDefination } from "@/types";

export const attackCards: CardDefination[] = [
  {
    definitionId: "attack_quick_attack",
    name: "Quick Attack",
    type: "attack",
    damage: 8,
    priority: 2,
    cooldown: 1,
    multiplier: "1x(default)",
  },
  {
    definitionId: "attack_precise_strike",
    name: "Precise Strike",
    type: "attack",
    damage: 10,
    priority: 1,
    cooldown: 1,
    multiplier: "2x if target has no Shield",
  },
  {
    definitionId: "attack_heavy_blow",
    name: "Heavy Blow",
    type: "attack",
    damage: 16,
    priority: 0,
    cooldown: 3,
    multiplier: "1x (default)",
    additional_effect: "User Gains Fatigue + 1",
    sideEffects: "Fatigue +1",
  },
  {
    definitionId: "attack_crushing_strike",
    name: "Crushing Strike",
    type: "attack",
    damage: 12,
    priority: 1,
    cooldown: 2,
    multiplier: "1.3x if target has Shield",
  },
  {
    definitionId: "attack_relentless_slash",
    name: "Relentless Slash",
    type: "attack",
    damage: 9,
    priority: 2,
    cooldown: 2,
    multiplier: "1x (default)",
  },
  {
    definitionId: "attack_exhausting_strike",
    name: "Exhausting Strike",
    type: "attack",
    damage: 7,
    priority: 1,
    cooldown: 2,
    multiplier: "1x (default)",
    additional_effect: "Applies fatigue + 1",
    sideEffects: "Fatigue +1",
  },
  {
    definitionId: "attack_opportunist_hit",
    name: "Opportunist Hit",
    type: "attack",
    damage: 11,
    priority: 2,
    cooldown: 2,
    multiplier: "1.4x if target has Fatigue",
  },
  {
    definitionId: "attack_all_in_strike",
    name: "All-In Strike",
    type: "attack",
    damage: 20,
    priority: 0,
    cooldown: 4,
    multiplier: "1x (default)",
    additional_effect: "User Gains Fatigue + 2",
    sideEffects: "Fatigue +2",
  },
];
