export const attackCards = [
  {
    name: "Quick Attack",
    type: "Attack",
    damage: 8,
    priority: 2,
    cooldown: 1,
    multiplier: "1x(default)",
  },
  {
    name: "Precise Strike",
    type: "Attack",
    damage: 10,
    priority: 1,
    cooldown: 1,
    multiplier: "2x if target has no Shield",
  },
  {
    name: "Heavy Blow",
    type: "Attack",
    damage: 16,
    priority: 0,
    cooldown: 3,
    multiplier: "1x (default)",
    additional_effect: "User Gains Fatigue + 1",
  },
  {
    name: "Crushing Strike",
    type: "Attack",
    damage: 12,
    priority: 1,
    cooldown: 2,
    multiplier: "1.3x if target has Shield",
  },
  {
    name: "Relentless Slash",
    type: "Attack",
    damage: 9,
    priority: 2,
    cooldown: 2,
    multiplier: "1x (default)",
  },
  {
    name: "Exhausting Strike",
    type: "Attack",
    damage: 7,
    priority: 1,
    cooldown: 2,
    multiplier: "1x (default)",
    additional_effect: "Applies fatigue + 1",
  },
  {
    name: "Opportunist Hit",
    type: "Attack",
    damage: 11,
    priority: 2,
    cooldown: 2,
    multiplier: "1.4x if target has Fatigue",
  },
  {
    name: "All-In Strike",
    type: "Attack",
    damage: 20,
    priority: 0,
    cooldown: 4,
    multiplier: "1x (default)",
    additional_effect: "User Gains Fatigue + 2",
  },
];
