import { CardDefination } from "@/types";

export const buffDebuffCards: CardDefination[] = [
  {
    definitionId: "buff_battle_focus",
    name: "Battle Focus",
    type: "buff",
    effect: "Increase damage of next attack card by +1x",
    multiplier: "+1x",
    cooldown: 3,
    priority: 3,
  },
  {
    definitionId: "buff_defensive_posture",
    name: "Defensive Posture",
    type: "buff",
    effect: "Increase next shield gain by +1x",
    multiplier: "+1x",
    cooldown: 3,
    priority: 3,
  },
  {
    definitionId: "buff_adrenaline_rush",
    name: "Adrenaline Rush",
    type: "buff",
    effect: "Reduce cooldown of next played card by 2 turn",
    multiplier: "-2 Cooldown",
    cooldown: 4,
    priority: 3,
  },
  {
    definitionId: "debuff_weaken",
    name: "Weaken",
    type: "debuff",
    effect: "Opponent's next Attack card deals 40% less damage",
    multiplier: "-0.4x",
    cooldown: 3,
    priority: 3,
  },
  {
    definitionId: "debuff_crippling_pressure",
    name: "Crippling Pressure",
    type: "debuff",
    effect: "Opponent's next Attack card damage reduced by 60%",
    multiplier: "-0.6x",
    cooldown: 4,
    priority: 3,
  },
  {
    definitionId: "debuff_guard_break_prep",
    name: "Guard Break Prep",
    type: "debuff",
    effect: "Lowers Opponents shield by half",
    multiplier: "Opponent shield -50%",
    cooldown: 4,
    priority: 3,
  },
];
