export const defenceCards = [
  {
    name: "Guard",
    type: "Defense",
    shield_gain: 8,
    priority: 2,
    cooldown: 1,
    multiplier: "1x",
  },
  {
    name: "Reinforced Guard",
    type: "Defense",
    shield_gain: 12,
    priority: 1,
    cooldown: 2,
    multiplier: "1x",
  },
  {
    name: "Brace",
    type: "Defense",
    shield_gain: 10,
    priority: 2,
    cooldown: 2,
    multiplier: "1x",
    additional_effect: "Reduces Fatigue - 1",
  },
  {
    name: "Fortify",
    type: "Defense",
    shield_gain: 15,
    priority: 0,
    cooldown: 3,
    multiplier: "1x",
  },
  {
    name: "Reactive Barrier",
    type: "Defense",
    shield_gain: 6,
    priority: 2,
    cooldown: 2,
    multiplier: "1x + 0.2x per Fatigue on self",
  },
  {
    name: "Iron Stance",
    type: "Defense",
    shield_gain: 10,
    priority: 2,
    cooldown: 3,
    multiplier: "1x",
    additional_effect: "User Fatigue + 1",
  },
];
